version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  
  apt_packages:
    - texlive-lang-chinese  # 中文支持
    - texlive-lang-japanese  # 日文支持
    - texlive-xetex  # XeLaTeX 引擎
    - fonts-noto-cjk
    - fonts-wqy-zenhei 
    - fonts-wqy-microhei
    - fonts-arphic-uming 
    - fonts-arphic-ukai

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  builder: html
  configuration: docs/source/conf.py

formats: all
